name: backend-ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: [starter/backend]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install pipenv and flake8
      run: |
        echo "Installing pipenv and flake8..."
        pip install pipenv flake8
    - name: Pipenv install
      run: |
        echo "Installing dependencies with pipenv..."
        cd starter/backend && pipenv install
    - name: Run lint
      run: |
        echo "Running lint with flake8..."
        cd starter/backend && pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install pipenv
      run: pip install pipenv
    - name: Pipenv install
      run: |
        echo "Installing dependencies with pipenv..."
        cd starter/backend && pipenv install
    - name: Run tests
      run: |
        echo "Running tests with pipenv..."
        cd starter/backend && pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install pipenv
      run: pip install pipenv
    - name: Build
      run: echo "Building application with Docker..."
