name: backend-ci
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: [starter/backend]


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: install pipenv
      run: |
        pip install pipenv 
        pip install flake8
    - name: pipenv install
      run: cd starter/backend && pipenv install
    - name: run tests
      run: cd starter/backend && pipenv run lint


  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: install pipenv
      run: pip install pipenv
    - name: pipenv install
      run: cd starter/backend && pipenv install
    - name: run tests
      run: cd starter/backend && pipenv run test        


  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: install pipenv tool
      run: pip install pipenv
    - name: build
      run: echo "docker build...."
