name: frontend-ci

on:
  pull_request:
    branches: [main]
    paths: [starter/frontend]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run lint
      run: |
        echo "Installing dependencies and running lint..."
        npm --prefix starter/frontend install
        npm --prefix starter/frontend run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        echo "Installing dependencies and running tests..."
        npm --prefix starter/frontend install
        CI=true npm --prefix starter/frontend test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run build
      run: |
        echo "Building application..."
        npm --prefix starter/frontend install
        CI=true npm --prefix starter/frontend run build
